#Ascendeum Task1 Shashwat Raj

In [ ]:
import numpy as np
def matr(n):
    mat=np.zeros((n,n),dtype =int)
    counter=1
    for i in range(n):
        mat[0][i]=counter
        counter+=1
    for i in range(1,n):
        mat[i][n-1]=counter
        counter+=1
    for i in range(n-2,-1,-1):
        mat[n-1][i]=counter
        counter+=1
    for i in range(n-2,0,-1):
        mat[i][0]=counter
        counter+=1
    for i in range(1,n-1):
        mat[1][i]=counter
        counter+=1
    for i in range(n-2,0,-1):
        mat[n-2][i]=counter
        counter+=1
    print(mat)
matr(4)


[[ 1  2  3  4]
 [12 13 14  5]
 [11 16 15  6]
 [10  9  8  7]]
